version: "3"

services:
  tgbot:
    container_name: bot
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - .:/src
    command: python echobot.py
    restart: always

